from flask import Flask, jsonify, request
from flask_cors import CORS
import json

app = Flask(__name__)
CORS(app)

# Azure resource types data
AZURE_RESOURCES = [
    "azurerm_aadb2c_directory",
    "azurerm_active_directory_domain_service",
    "azurerm_active_directory_domain_service_replica_set",
    "azurerm_active_directory_domain_service_trust",
    "azurerm_advanced_threat_protection",
    "azurerm_advisor_suppression",
    "azurerm_ai_foundry",
    "azurerm_ai_foundry_project",
    "azurerm_ai_services",
    "azurerm_analysis_services_server",
    "azurerm_api_connection",
    "azurerm_api_management",
    "azurerm_api_management_api",
    "azurerm_api_management_api_diagnostic",
    "azurerm_api_management_api_operation",
    "azurerm_api_management_api_operation_policy",
    "azurerm_api_management_api_operation_tag",
    "azurerm_api_management_api_policy",
    "azurerm_api_management_api_release",
    "azurerm_api_management_api_schema",
    "azurerm_api_management_api_tag",
    "azurerm_api_management_api_tag_description",
    "azurerm_api_management_api_version_set",
    "azurerm_api_management_authorization_server",
    "azurerm_api_management_backend",
    "azurerm_api_management_certificate",
    "azurerm_api_management_custom_domain",
    "azurerm_api_management_diagnostic",
    "azurerm_api_management_email_template",
    "azurerm_api_management_gateway",
    "azurerm_api_management_gateway_api",
    "azurerm_api_management_gateway_certificate_authority",
    "azurerm_api_management_gateway_host_name_configuration",
    "azurerm_api_management_global_schema",
    "azurerm_api_management_group",
    "azurerm_api_management_group_user",
    "azurerm_api_management_identity_provider_aad",
    "azurerm_api_management_identity_provider_aadb2c",
    "azurerm_api_management_identity_provider_facebook",
    "azurerm_api_management_identity_provider_google",
    "azurerm_api_management_identity_provider_microsoft",
    "azurerm_api_management_identity_provider_twitter",
    "azurerm_api_management_logger",
    "azurerm_api_management_named_value",
    "azurerm_api_management_notification_recipient_email",
    "azurerm_api_management_notification_recipient_user",
    "azurerm_api_management_openid_connect_provider",
    "azurerm_api_management_policy",
    "azurerm_api_management_policy_fragment",
    "azurerm_api_management_product",
    "azurerm_api_management_product_api",
    "azurerm_api_management_product_group",
    "azurerm_api_management_product_policy",
    "azurerm_api_management_product_tag",
    "azurerm_api_management_redis_cache",
    "azurerm_api_management_standalone_gateway",
    "azurerm_api_management_subscription",
    "azurerm_api_management_tag",
    "azurerm_api_management_user",
    "azurerm_api_management_workspace",
    "azurerm_api_management_workspace_api_version_set",
    "azurerm_api_management_workspace_certificate",
    "azurerm_api_management_workspace_policy",
    "azurerm_api_management_workspace_policy_fragment",
    "azurerm_app_configuration",
    "azurerm_app_configuration_feature",
    "azurerm_app_configuration_key",
    "azurerm_app_service",
    "azurerm_app_service_active_slot",
    "azurerm_app_service_certificate",
    "azurerm_app_service_certificate_binding",
    "azurerm_app_service_certificate_order",
    "azurerm_app_service_connection",
    "azurerm_app_service_custom_hostname_binding",
    "azurerm_app_service_environment_v3",
    "azurerm_app_service_hybrid_connection",
    "azurerm_app_service_managed_certificate",
    "azurerm_app_service_plan",
    "azurerm_app_service_public_certificate",
    "azurerm_app_service_slot",
    "azurerm_app_service_slot_custom_hostname_binding",
    "azurerm_app_service_slot_virtual_network_swift_connection",
    "azurerm_app_service_source_control",
    "azurerm_app_service_source_control_slot",
    "azurerm_app_service_source_control_token",
    "azurerm_app_service_virtual_network_swift_connection",
    "azurerm_application_gateway",
    "azurerm_application_insights",
    "azurerm_application_insights_analytics_item",
    "azurerm_application_insights_api_key",
    "azurerm_application_insights_smart_detection_rule",
    "azurerm_application_insights_standard_web_test",
    "azurerm_application_insights_web_test",
    "azurerm_application_insights_workbook",
    "azurerm_application_insights_workbook_template",
    "azurerm_application_load_balancer",
    "azurerm_application_load_balancer_frontend",
    "azurerm_application_load_balancer_security_policy",
    "azurerm_application_load_balancer_subnet_association",
    "azurerm_application_security_group",
    "azurerm_arc_kubernetes_cluster",
    "azurerm_arc_kubernetes_cluster_extension",
    "azurerm_arc_kubernetes_flux_configuration",
    "azurerm_arc_kubernetes_provisioned_cluster",
    "azurerm_arc_machine",
    "azurerm_arc_machine_automanage_configuration_assignment",
    "azurerm_arc_machine_extension",
    "azurerm_arc_private_link_scope",
    "azurerm_arc_resource_bridge_appliance",
    "azurerm_attestation_provider",
    "azurerm_automanage_configuration",
    "azurerm_automation_account",
    "azurerm_automation_certificate",
    "azurerm_automation_connection",
    "azurerm_automation_connection_certificate",
    "azurerm_automation_connection_classic_certificate",
    "azurerm_automation_connection_service_principal",
    "azurerm_automation_connection_type",
    "azurerm_automation_credential",
    "azurerm_automation_dsc_configuration",
    "azurerm_automation_dsc_nodeconfiguration",
    "azurerm_automation_hybrid_runbook_worker",
    "azurerm_automation_hybrid_runbook_worker_group",
    "azurerm_automation_job_schedule",
    "azurerm_automation_module",
    "azurerm_automation_powershell72_module",
    "azurerm_automation_python3_package",
    "azurerm_automation_runbook",
    "azurerm_automation_schedule",
    "azurerm_automation_software_update_configuration",
    "azurerm_automation_source_control",
    "azurerm_automation_variable_bool",
    "azurerm_automation_variable_datetime",
    "azurerm_automation_variable_int",
    "azurerm_automation_variable_object",
    "azurerm_automation_variable_string",
    "azurerm_automation_watcher",
    "azurerm_automation_webhook",
    "azurerm_availability_set",
    "azurerm_backup_container_storage_account",
    "azurerm_backup_policy_file_share",
    "azurerm_backup_policy_vm",
    "azurerm_backup_policy_vm_workload",
    "azurerm_backup_protected_file_share",
    "azurerm_backup_protected_vm",
    "azurerm_bastion_host",
    "azurerm_batch_account",
    "azurerm_batch_application",
    "azurerm_batch_certificate",
    "azurerm_batch_job",
    "azurerm_batch_pool",
    "azurerm_billing_account_cost_management_export",
    "azurerm_blueprint_assignment",
    "azurerm_bot_channel_alexa",
    "azurerm_bot_channel_direct_line_speech",
    "azurerm_bot_channel_directline",
    "azurerm_bot_channel_email",
    "azurerm_bot_channel_facebook",
    "azurerm_bot_channel_line",
    "azurerm_bot_channel_ms_teams",
    "azurerm_bot_channel_slack",
    "azurerm_bot_channel_sms",
    "azurerm_bot_channel_web_chat",
    "azurerm_bot_channels_registration",
    "azurerm_bot_connection",
    "azurerm_bot_service_azure_bot",
    "azurerm_bot_web_app",
    "azurerm_capacity_reservation",
    "azurerm_capacity_reservation_group",
    "azurerm_cdn_endpoint",
    "azurerm_cdn_endpoint_custom_domain",
    "azurerm_cdn_frontdoor_custom_domain",
    "azurerm_cdn_frontdoor_custom_domain_association",
    "azurerm_cdn_frontdoor_endpoint",
    "azurerm_cdn_frontdoor_firewall_policy",
    "azurerm_cdn_frontdoor_origin",
    "azurerm_cdn_frontdoor_origin_group",
    "azurerm_cdn_frontdoor_profile",
    "azurerm_cdn_frontdoor_route",
    "azurerm_cdn_frontdoor_rule",
    "azurerm_cdn_frontdoor_rule_set",
    "azurerm_cdn_frontdoor_secret",
    "azurerm_cdn_frontdoor_security_policy",
    "azurerm_cdn_profile",
    "azurerm_chaos_studio_capability",
    "azurerm_chaos_studio_experiment",
    "azurerm_chaos_studio_target",
    "azurerm_cognitive_account",
    "azurerm_cognitive_account_customer_managed_key",
    "azurerm_cognitive_account_rai_blocklist",
    "azurerm_cognitive_account_rai_policy",
    "azurerm_cognitive_deployment",
    "azurerm_communication_service",
    "azurerm_communication_service_email_domain_association",
    "azurerm_confidential_ledger",
    "azurerm_consumption_budget_management_group",
    "azurerm_consumption_budget_resource_group",
    "azurerm_consumption_budget_subscription",
    "azurerm_container_app",
    "azurerm_container_app_custom_domain",
    "azurerm_container_app_environment",
    "azurerm_container_app_environment_certificate",
    "azurerm_container_app_environment_custom_domain",
    "azurerm_container_app_environment_dapr_component",
    "azurerm_container_app_environment_storage",
    "azurerm_container_app_job",
    "azurerm_container_connected_registry",
    "azurerm_container_group",
    "azurerm_container_registry",
    "azurerm_container_registry_agent_pool",
    "azurerm_container_registry_cache_rule",
    "azurerm_container_registry_credential_set",
    "azurerm_container_registry_scope_map",
    "azurerm_container_registry_task",
    "azurerm_container_registry_task_schedule_run_now",
    "azurerm_container_registry_token",
    "azurerm_container_registry_token_password",
    "azurerm_container_registry_webhook",
    "azurerm_cosmosdb_account",
    "azurerm_cosmosdb_cassandra_cluster",
    "azurerm_cosmosdb_cassandra_datacenter",
    "azurerm_cosmosdb_cassandra_keyspace",
    "azurerm_cosmosdb_cassandra_table",
    "azurerm_cosmosdb_gremlin_database",
    "azurerm_cosmosdb_gremlin_graph",
    "azurerm_cosmosdb_mongo_collection",
    "azurerm_cosmosdb_mongo_database",
    "azurerm_cosmosdb_mongo_role_definition",
    "azurerm_cosmosdb_mongo_user_definition",
    "azurerm_cosmosdb_postgresql_cluster",
    "azurerm_cosmosdb_postgresql_coordinator_configuration",
    "azurerm_cosmosdb_postgresql_firewall_rule",
    "azurerm_cosmosdb_postgresql_node_configuration",
    "azurerm_cosmosdb_postgresql_role",
    "azurerm_cosmosdb_sql_container",
    "azurerm_cosmosdb_sql_database",
    "azurerm_cosmosdb_sql_dedicated_gateway",
    "azurerm_cosmosdb_sql_function",
    "azurerm_cosmosdb_sql_role_assignment",
    "azurerm_cosmosdb_sql_role_definition",
    "azurerm_cosmosdb_sql_stored_procedure",
    "azurerm_cosmosdb_sql_trigger",
    "azurerm_cosmosdb_table",
    "azurerm_cost_anomaly_alert",
    "azurerm_cost_management_scheduled_action",
    "azurerm_custom_ip_prefix",
    "azurerm_custom_provider",
    "azurerm_dashboard_grafana",
    "azurerm_dashboard_grafana_managed_private_endpoint",
    "azurerm_data_factory",
    "azurerm_data_factory_credential_service_principal",
    "azurerm_data_factory_credential_user_managed_identity",
    "azurerm_data_factory_custom_dataset",
    "azurerm_data_factory_customer_managed_key",
    "azurerm_data_factory_data_flow",
    "azurerm_data_factory_dataset_azure_blob",
    "azurerm_data_factory_dataset_azure_sql_table",
    "azurerm_data_factory_dataset_binary",
    "azurerm_data_factory_dataset_cosmosdb_sqlapi",
    "azurerm_data_factory_dataset_delimited_text",
    "azurerm_data_factory_dataset_http",
    "azurerm_data_factory_dataset_json",
    "azurerm_data_factory_dataset_mysql",
    "azurerm_data_factory_dataset_parquet",
    "azurerm_data_factory_dataset_postgresql",
    "azurerm_data_factory_dataset_snowflake",
    "azurerm_data_factory_dataset_sql_server_table",
    "azurerm_data_factory_flowlet_data_flow",
    "azurerm_data_factory_integration_runtime_azure",
    "azurerm_data_factory_integration_runtime_azure_ssis",
    "azurerm_data_factory_integration_runtime_self_hosted",
    "azurerm_data_factory_linked_custom_service",
    "azurerm_data_factory_linked_service_azure_blob_storage",
    "azurerm_data_factory_linked_service_azure_databricks",
    "azurerm_data_factory_linked_service_azure_file_storage",
    "azurerm_data_factory_linked_service_azure_function",
    "azurerm_data_factory_linked_service_azure_search",
    "azurerm_data_factory_linked_service_azure_sql_database",
    "azurerm_data_factory_linked_service_azure_table_storage",
    "azurerm_data_factory_linked_service_cosmosdb",
    "azurerm_data_factory_linked_service_cosmosdb_mongoapi",
    "azurerm_data_factory_linked_service_data_lake_storage_gen2",
    "azurerm_data_factory_linked_service_key_vault",
    "azurerm_data_factory_linked_service_kusto",
    "azurerm_data_factory_linked_service_mysql",
    "azurerm_data_factory_linked_service_odata",
    "azurerm_data_factory_linked_service_odbc",
    "azurerm_data_factory_linked_service_postgresql",
    "azurerm_data_factory_linked_service_sftp",
    "azurerm_data_factory_linked_service_snowflake",
    "azurerm_data_factory_linked_service_sql_server",
    "azurerm_data_factory_linked_service_synapse",
    "azurerm_data_factory_linked_service_web",
    "azurerm_data_factory_managed_private_endpoint",
    "azurerm_data_factory_pipeline",
    "azurerm_data_factory_trigger_blob_event",
    "azurerm_data_factory_trigger_custom_event",
    "azurerm_data_factory_trigger_schedule",
    "azurerm_data_factory_trigger_tumbling_window",
    "azurerm_data_protection_backup_instance_blob_storage",
    "azurerm_data_protection_backup_instance_disk",
    "azurerm_data_protection_backup_instance_kubernetes_cluster",
    "azurerm_data_protection_backup_instance_mysql_flexible_server",
    "azurerm_data_protection_backup_instance_postgresql",
    "azurerm_data_protection_backup_instance_postgresql_flexible_server",
    "azurerm_data_protection_backup_policy_blob_storage",
    "azurerm_data_protection_backup_policy_disk",
    "azurerm_data_protection_backup_policy_kubernetes_cluster",
    "azurerm_data_protection_backup_policy_mysql_flexible_server",
    "azurerm_data_protection_backup_policy_postgresql",
    "azurerm_data_protection_backup_policy_postgresql_flexible_server",
    "azurerm_data_protection_backup_vault",
    "azurerm_data_protection_backup_vault_customer_managed_key",
    "azurerm_data_protection_resource_guard",
    "azurerm_data_share",
    "azurerm_data_share_account",
    "azurerm_data_share_dataset_blob_storage",
    "azurerm_data_share_dataset_data_lake_gen2",
    "azurerm_data_share_dataset_kusto_cluster",
    "azurerm_data_share_dataset_kusto_database",
    "azurerm_database_migration_project",
    "azurerm_database_migration_service",
    "azurerm_databox_edge_device",
    "azurerm_databricks_access_connector",
    "azurerm_databricks_virtual_network_peering",
    "azurerm_databricks_workspace",
    "azurerm_databricks_workspace_customer_managed_key",
    "azurerm_databricks_workspace_root_dbfs_customer_managed_key",
    "azurerm_datadog_monitor",
    "azurerm_datadog_monitor_sso_configuration",
    "azurerm_datadog_monitor_tag_rule",
    "azurerm_dedicated_hardware_security_module",
    "azurerm_dedicated_host",
    "azurerm_dedicated_host_group",
    "azurerm_dev_center",
    "azurerm_dev_center_attached_network",
    "azurerm_dev_center_catalog",
    "azurerm_dev_center_dev_box_definition",
    "azurerm_dev_center_environment_type",
    "azurerm_dev_center_gallery",
    "azurerm_dev_center_network_connection",
    "azurerm_dev_center_project",
    "azurerm_dev_center_project_environment_type",
    "azurerm_dev_center_project_pool",
    "azurerm_dev_test_global_vm_shutdown_schedule",
    "azurerm_dev_test_lab",
    "azurerm_dev_test_linux_virtual_machine",
    "azurerm_dev_test_policy",
    "azurerm_dev_test_schedule",
    "azurerm_dev_test_virtual_network",
    "azurerm_dev_test_windows_virtual_machine",
    "azurerm_digital_twins_endpoint_eventgrid",
    "azurerm_digital_twins_endpoint_eventhub",
    "azurerm_digital_twins_endpoint_servicebus",
    "azurerm_digital_twins_instance",
    "azurerm_digital_twins_time_series_database_connection",
    "azurerm_disk_access",
    "azurerm_disk_encryption_set",
    "azurerm_dns_a_record",
    "azurerm_dns_aaaa_record",
    "azurerm_dns_caa_record",
    "azurerm_dns_cname_record",
    "azurerm_dns_mx_record",
    "azurerm_dns_ns_record",
    "azurerm_dns_ptr_record",
    "azurerm_dns_srv_record",
    "azurerm_dns_txt_record",
    "azurerm_dns_zone",
    "azurerm_dynatrace_monitor",
    "azurerm_dynatrace_tag_rules",
    "azurerm_elastic_cloud_elasticsearch",
    "azurerm_elastic_san",
    "azurerm_elastic_san_volume",
    "azurerm_elastic_san_volume_group",
    "azurerm_email_communication_service",
    "azurerm_email_communication_service_domain",
    "azurerm_email_communication_service_domain_sender_username",
    "azurerm_eventgrid_domain",
    "azurerm_eventgrid_domain_topic",
    "azurerm_eventgrid_event_subscription",
    "azurerm_eventgrid_namespace",
    "azurerm_eventgrid_partner_configuration",
    "azurerm_eventgrid_partner_namespace",
    "azurerm_eventgrid_partner_registration",
    "azurerm_eventgrid_system_topic",
    "azurerm_eventgrid_system_topic_event_subscription",
    "azurerm_eventgrid_topic",
    "azurerm_eventhub",
    "azurerm_eventhub_authorization_rule",
    "azurerm_eventhub_cluster",
    "azurerm_eventhub_consumer_group",
    "azurerm_eventhub_namespace",
    "azurerm_eventhub_namespace_authorization_rule",
    "azurerm_eventhub_namespace_customer_managed_key",
    "azurerm_eventhub_namespace_disaster_recovery_config",
    "azurerm_eventhub_namespace_schema_group",
    "azurerm_express_route_circuit",
    "azurerm_express_route_circuit_authorization",
    "azurerm_express_route_circuit_connection",
    "azurerm_express_route_circuit_peering",
    "azurerm_express_route_connection",
    "azurerm_express_route_gateway",
    "azurerm_express_route_port",
    "azurerm_express_route_port_authorization",
    "azurerm_extended_custom_location",
    "azurerm_extended_location_custom_location",
    "azurerm_fabric_capacity",
    "azurerm_federated_identity_credential",
    "azurerm_firewall",
    "azurerm_firewall_application_rule_collection",
    "azurerm_firewall_nat_rule_collection",
    "azurerm_firewall_network_rule_collection",
    "azurerm_firewall_policy",
    "azurerm_firewall_policy_rule_collection_group",
    "azurerm_fluid_relay_server",
    "azurerm_frontdoor",
    "azurerm_frontdoor_custom_https_configuration",
    "azurerm_frontdoor_firewall_policy",
    "azurerm_frontdoor_rules_engine",
    "azurerm_function_app",
    "azurerm_function_app_active_slot",
    "azurerm_function_app_connection",
    "azurerm_function_app_flex_consumption",
    "azurerm_function_app_function",
    "azurerm_function_app_hybrid_connection",
    "azurerm_function_app_slot",
    "azurerm_gallery_application",
    "azurerm_gallery_application_version",
    "azurerm_graph_services_account",
    "azurerm_hdinsight_hadoop_cluster",
    "azurerm_hdinsight_hbase_cluster",
    "azurerm_hdinsight_interactive_query_cluster",
    "azurerm_hdinsight_kafka_cluster",
    "azurerm_hdinsight_spark_cluster",
    "azurerm_healthbot",
    "azurerm_healthcare_dicom_service",
    "azurerm_healthcare_fhir_service",
    "azurerm_healthcare_medtech_service",
    "azurerm_healthcare_medtech_service_fhir_destination",
    "azurerm_healthcare_service",
    "azurerm_healthcare_workspace",
    "azurerm_hpc_cache",
    "azurerm_hpc_cache_access_policy",
    "azurerm_hpc_cache_blob_nfs_target",
    "azurerm_hpc_cache_blob_target",
    "azurerm_hpc_cache_nfs_target",
    "azurerm_image",
    "azurerm_iot_security_device_group",
    "azurerm_iot_security_solution",
    "azurerm_iotcentral_application",
    "azurerm_iotcentral_application_network_rule_set",
    "azurerm_iotcentral_organization",
    "azurerm_iothub",
    "azurerm_iothub_certificate",
    "azurerm_iothub_consumer_group",
    "azurerm_iothub_device_update_account",
    "azurerm_iothub_device_update_instance",
    "azurerm_iothub_dps",
    "azurerm_iothub_dps_certificate",
    "azurerm_iothub_dps_shared_access_policy",
    "azurerm_iothub_endpoint_cosmosdb_account",
    "azurerm_iothub_endpoint_eventhub",
    "azurerm_iothub_endpoint_servicebus_queue",
    "azurerm_iothub_endpoint_servicebus_topic",
    "azurerm_iothub_endpoint_storage_container",
    "azurerm_iothub_enrichment",
    "azurerm_iothub_fallback_route",
    "azurerm_iothub_file_upload",
    "azurerm_iothub_route",
    "azurerm_iothub_shared_access_policy",
    "azurerm_ip_group",
    "azurerm_ip_group_cidr",
    "azurerm_key_vault",
    "azurerm_key_vault_access_policy",
    "azurerm_key_vault_certificate",
    "azurerm_key_vault_certificate_contacts",
    "azurerm_key_vault_certificate_issuer",
    "azurerm_key_vault_key",
    "azurerm_key_vault_managed_hardware_security_module",
    "azurerm_key_vault_managed_hardware_security_module_key",
    "azurerm_key_vault_managed_hardware_security_module_key_rotation_policy",
    "azurerm_key_vault_managed_hardware_security_module_role_assignment",
    "azurerm_key_vault_managed_hardware_security_module_role_definition",
    "azurerm_key_vault_managed_storage_account",
    "azurerm_key_vault_managed_storage_account_sas_token_definition",
    "azurerm_key_vault_secret",
    "azurerm_kubernetes_cluster",
    "azurerm_kubernetes_cluster_extension",
    "azurerm_kubernetes_cluster_node_pool",
    "azurerm_kubernetes_cluster_trusted_access_role_binding",
    "azurerm_kubernetes_fleet_manager",
    "azurerm_kubernetes_fleet_member",
    "azurerm_kubernetes_fleet_update_run",
    "azurerm_kubernetes_fleet_update_strategy",
    "azurerm_kubernetes_flux_configuration",
    "azurerm_kusto_attached_database_configuration",
    "azurerm_kusto_cluster",
    "azurerm_kusto_cluster_customer_managed_key",
    "azurerm_kusto_cluster_managed_private_endpoint",
    "azurerm_kusto_cluster_principal_assignment",
    "azurerm_kusto_cosmosdb_data_connection",
    "azurerm_kusto_database",
    "azurerm_kusto_database_principal_assignment",
    "azurerm_kusto_eventgrid_data_connection",
    "azurerm_kusto_eventhub_data_connection",
    "azurerm_kusto_iothub_data_connection",
    "azurerm_kusto_script",
    "azurerm_lb",
    "azurerm_lb_backend_address_pool",
    "azurerm_lb_backend_address_pool_address",
    "azurerm_lb_nat_pool",
    "azurerm_lb_nat_rule",
    "azurerm_lb_outbound_rule",
    "azurerm_lb_probe",
    "azurerm_lb_rule",
    "azurerm_lighthouse_assignment",
    "azurerm_lighthouse_definition",
    "azurerm_linux_function_app",
    "azurerm_linux_function_app_slot",
    "azurerm_linux_virtual_machine",
    "azurerm_linux_virtual_machine_scale_set",
    "azurerm_linux_web_app",
    "azurerm_linux_web_app_slot",
    "azurerm_load_test",
    "azurerm_local_network_gateway",
    "azurerm_log_analytics_cluster",
    "azurerm_log_analytics_cluster_customer_managed_key",
    "azurerm_log_analytics_data_export_rule",
    "azurerm_log_analytics_datasource_windows_event",
    "azurerm_log_analytics_datasource_windows_performance_counter"
]

@app.route('/')
def home():
    """API documentation"""
    return jsonify({
        "name": "Azure Resource Types API",
        "version": "4.53.0",
        "description": "API for Azure Terraform resource types",
        "endpoints": {
            "/api/resources": "GET all resource types",
            "/api/resources/count": "GET total count",
            "/api/resources/search?q=<query>": "Search resource types",
            "/api/resources/category/<category>": "Filter by category"
        }
    })

@app.route('/api/resources', methods=['GET'])
def get_all_resources():
    """Return all Azure resource types"""
    return jsonify({
        "total": len(AZURE_RESOURCES),
        "resources": AZURE_RESOURCES
    })

@app.route('/api/resources/count', methods=['GET'])
def get_count():
    """Return the total count of resource types"""
    return jsonify({
        "count": len(AZURE_RESOURCES)
    })

@app.route('/api/resources/search', methods=['GET'])
def search_resources():
    """Search for resource types by query parameter"""
    query = request.args.get('q', '').lower()
    
    if not query:
        return jsonify({"error": "Query parameter 'q' is required"}), 400
    
    results = [r for r in AZURE_RESOURCES if query in r.lower()]
    
    return jsonify({
        "query": query,
        "count": len(results),
        "results": results
    })

@app.route('/api/resources/category/<category>', methods=['GET'])
def get_by_category(category):
    """Filter resources by category (e.g., 'storage', 'network', 'compute')"""
    category = category.lower()
    
    # Filter resources containing the category name
    results = [r for r in AZURE_RESOURCES if category in r.lower()]
    
    return jsonify({
        "category": category,
        "count": len(results),
        "results": results
    })

if __name__ == '__main__':
    print("\n" + "="*60)
    print("Azure Resource Types API Server")
    print("="*60)
    print("\nAPI Endpoints:")
    print("- http://localhost:5000/")
    print("- http://localhost:5000/api/resources")
    print("- http://localhost:5000/api/resources/count")
    print("- http://localhost:5000/api/resources/search?q=storage")
    print("- http://localhost:5000/api/resources/category/network")
    print("\nPress CTRL+C to stop")
    print("="*60 + "\n")
    
    app.run(debug=True, host='0.0.0.0', port=5000)
    